module.exports = [
    "HUGH'S YOUR DADDY!?",
    'DRANK RED RUM',
    "KORIC'D",
    'MET MIDJIWAN',
    'FOLLOWED REAPERSTORMENT',
    'BUSTED',
    "OLD BARDUR'D",
    'BOTHERED NELLUK',
    'PINGED LUNA',
    'HUGGED',
    'REKT',
    'SNUFFED',
    'WRECKED',
    'JAMED',
    'SLAIN',
    'SHREDDED',
    'BIG OOF',
    'SCHOOLED',
    'SHELLED',
    'SMOKED',
    'NOOTED',
];
