module.exports = ['DRANK RED RUM',
    'KORIC\'D',
    'MET MIDJIWAN',
    'FOLLOWED REAPERSTORMENT',
    'CLEANED',
    'BLASTED',
    'SHATTERED',
    'TOTALED',
    'TRASHED',
    'THRASHED',
    'BUSTED',
    'CLEAVED',
    'OLD BARDUR\'D',
    'VITIATED',
    'NULLIFIED',
    'ANNULED',
    'PINGED NELLUK',
    'SQUASHED',
    'DETONATED',
    'ROASTED',
    'HUGGED',
    'GORED',
    'REKT',
    'REMOVED',
    'GUTTED',
    'PUT DOWN',
    'SNUFFED',
    'ICED',
    'WRECKED',
    'JAMED',
    'SLAIN',
    'SHREDDED',
    'BIG OOF',
    'DECIMATED',
    'CRUSHED',
    'BLENDED',
    'DESTROYED',
    'MAULED',
    'SCHOOLED',
    'SHELLED',
    'DEAD',
    'ELIMINATED',
    'MURDERED',
    'STEAMED',
    'SMOKED',
    'DELETED']//,
//  'SHIVVED',
//  'NEUTRALIZED',
//  'SCRATCHED',
//  'MASSACRED',
//  'DESTROZADO',
//  'SPINDLED',
//  'FOLDED',
//  'MUTILATED',
//  'STAPLED',
//  'CLIPPED',
//  'WARPED',
//  'DISMEMBERED',
//  'DECAPITATED',
//  'IRONED',
//  'INCINERATED',
//  'BOMBED',
//  'SQUEEGEED',
//  'VACUMMED',
//  'DISSECTED',
//  'TORPEDOED',
//  'SPLINTERED',
//  'FRAGMENTED',
//  'BATTERED',
//  'SPITTED',    
//  'GRATED',
//  'FLAYED',
//  'SNIPED',
//  'REDACTED',
//  'ASPHYXIATED',
//  'CAPPED',
//  'CONDENSED',
//  'STEAMROLLED',
//  'FLATTENED',
//  'DISSOLVED'