-- PolyCalculator schema: the three live tables (stats, servers, units) plus a
-- lightweight counter for milestone announcements.
--
-- Column types mirror the existing production database exactly (captured via
-- information_schema dump) so a data-only restore loads cleanly. The orphan
-- tables from the old DB (premium, advisors) and the derived views
-- (last_7_days, total_*) are intentionally NOT recreated — they have no code.

-- ---------------------------------------------------------------------------
-- stats: append-only usage log. One row per command invocation.
-- `id` is "by default" (not "always") identity so a --data-only restore can
-- supply explicit ids from the old database; the sequence is reset afterward.
-- ---------------------------------------------------------------------------
create table if not exists public.stats (
    id                   bigint generated by default as identity primary key,
    content              varchar     not null,
    author_id            varchar     not null,
    author_tag           varchar,
    command              varchar,
    attacker             varchar,
    defender             varchar,
    url                  varchar,
    server_id            varchar,
    will_delete          boolean,
    is_attacker_vet      boolean,
    is_defender_vet      boolean,
    attacker_description varchar,
    defender_description varchar,
    reply_fields         varchar[],
    arg                  varchar,
    message_id           varchar,
    is_slash             boolean,
    created_at           timestamptz default now()
);

-- Composite index serves both /stats COUNT queries:
--   WHERE author_id = $1 AND server_id = $2   (uses the full index)
--   WHERE author_id = $1                       (uses the leading column)
create index if not exists idx_stats_author_server
    on public.stats (author_id, server_id);

-- ---------------------------------------------------------------------------
-- servers: derived guild presence. Upserted on every interaction using the
-- guild_id in the Discord payload (no gateway guildCreate/Delete events).
-- `last_seen` is new in the serverless design.
-- ---------------------------------------------------------------------------
create table if not exists public.servers (
    server_id    varchar primary key,
    server_name  varchar,
    bot_channels varchar[],
    active       boolean     default true,
    last_seen    timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- units: NOT read by the combat engine (unitsList.js is source of truth).
-- Kept only to back a future public API (calc-api /units list mode).
-- ---------------------------------------------------------------------------
create table if not exists public.units (
    code                varchar primary key,
    name                varchar not null,
    plural              varchar not null,
    maxhp               int,
    vet                 boolean,
    att                 real    not null,
    def                 real    not null,
    fort                boolean not null,
    range               boolean not null,
    retaliation         boolean not null,
    boardable           boolean not null,
    is_naval_unit       boolean not null,
    unit_type           varchar,
    unit_type_priority  int,
    poison_attack       boolean,
    can_explode         boolean,
    poison_explode      boolean,
    unit_priority       int
);

-- ---------------------------------------------------------------------------
-- stats_total: single-row counter. Incremented in the same transaction as a
-- stats insert (see bump_stats_total RPC) so the milestone check is O(1)
-- instead of COUNT(*) over hundreds of thousands of rows on every command.
-- ---------------------------------------------------------------------------
create table if not exists public.stats_total (
    id    boolean primary key default true,
    total bigint  not null    default 0,
    constraint stats_total_singleton check (id)
);

insert into public.stats_total (id, total)
    values (true, 0)
    on conflict (id) do nothing;

-- Atomically increment and return the new total. The interactions function
-- calls this after inserting a stats row; a return value divisible by 25000
-- triggers the milestone announcement.
create or replace function public.bump_stats_total()
returns bigint
language sql
as $$
    update public.stats_total
       set total = total + 1
     where id = true
    returning total;
$$;
