name: CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                shard: [1, 2, 3, 4]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - name: Install dependencies
              run: npm ci

            - name: Lint the code
              if: matrix.shard == 1
              run: npm run lint

            - name: Run tests
              run: npm test -- --shard=${{ matrix.shard }}/4

    deploy:
        needs: build
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: cd /apps/PolyCalculator && git pull --all && sudo systemctl restart calc
